# Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada.
t = int(input("Digite um número para sabermos sua tabuada: "))
print('-' * 15)
print(f"{t} x  1 = {t:>2}")
print(f"{t} x  2 = {t*2:>2}")
print(f"{t} x  3 = {t*3:>2}")
print(f"{t} x  4 = {t*4:>2}")
print(f"{t} x  5 = {t*5:>2}")
print(f"{t} x  6 = {t*6:>2}")
print(f"{t} x  7 = {t*7:>2}")
print(f"{t} x  8 = {t*8:>2}")
print(f"{t} x  9 = {t*9:>2}")
print(f"{t} x 10 = {t*10}")
print('-' * 15)
